set_false_path -from [get_pins axi_rst_st0_n_reg/C] -to [get_pins *axi_rst0_st0_r1_n_reg/D]
set_false_path -from [get_pins axi_rst_st0_n_reg/C] -to [get_pins *axi_rst1_st0_r1_n_reg/D]
set_false_path -from [get_pins axi_rst_st0_n_reg/C] -to [get_pins *axi_rst2_st0_r1_n_reg/D]
set_false_path -from [get_pins axi_rst_st0_n_reg/C] -to [get_pins *axi_rst3_st0_r1_n_reg/D]
set_false_path -from [get_pins axi_rst_st0_n_reg/C] -to [get_pins *axi_rst4_st0_r1_n_reg/D]
set_false_path -from [get_pins axi_rst_st0_n_reg/C] -to [get_pins *axi_rst5_st0_r1_n_reg/D]
set_false_path -from [get_pins axi_rst_st0_n_reg/C] -to [get_pins *axi_rst6_st0_r1_n_reg/D]

set_false_path -from [get_pins */*/*/*/apb_switch_r_reg/C] -to [get_pins *apb_seq_complete_0_st0_r0_reg/D]
set_false_path -from [get_pins */*/*/*/apb_switch_r_reg/C] -to [get_pins *apb_seq_complete_1_st0_r0_reg/D]
set_false_path -from [get_pins */*/*/*/apb_switch_r_reg/C] -to [get_pins *apb_seq_complete_2_st0_r0_reg/D]
set_false_path -from [get_pins */*/*/*/apb_switch_r_reg/C] -to [get_pins *apb_seq_complete_3_st0_r0_reg/D]
set_false_path -from [get_pins */*/*/*/apb_switch_r_reg/C] -to [get_pins *apb_seq_complete_4_st0_r0_reg/D]
set_false_path -from [get_pins */*/*/*/apb_switch_r_reg/C] -to [get_pins *apb_seq_complete_5_st0_r0_reg/D]
set_false_path -from [get_pins */*/*/*/apb_switch_r_reg/C] -to [get_pins *apb_seq_complete_6_st0_r0_reg/D]

set_false_path -from [get_cells -hier -filter {name =~ *reset_debounce*/o_r*}] -to [get_cells -hier -filter {name =~ *_RST_N/pipe*}]